### ISSUE TITLE
Cuda Runtime (out of memory) issue when running with TensorRT on RTX 4090 with small strength

### ISSUE THREAD

**Issue by marghovo** [open-mmlab/Live2Diff#9]
Hi, 

Thanks for the interesting work. I am trying to run live2diff with TensorRT on RTX 4090 (`cuda 12.2`). However I am getting `Cuda Runtime (out of memory)` issue. Reducing the strength, number of inference steps or t_index_list does not help. I still get this issue with very small strength. This issue then results in `AttributeError: 'NoneType' object has no attribute 'set_input_shape'`. I have followed your installation instructions.  Do you know how I can resolve this issue?

Thanks in advance.

**Comment by LeoXing1996** [comment]
Hi @marghovo, it looks like the `AttributeError: 'NoneType' object has no attribute 'set_input_shape'` error is occurring because `Engine.activate` wasn't called successfully. Could you share the full output of the code when you run it? That way, I’ll be able to assist you more effectively.

**Comment by marghovo** [comment]
Hi @LeoXing1996 . Thanks for your response. Please see the output of the code when running with `num_inference_steps: 10 t_index_list: [0, 2, 4] strength: 1` below. 

```
/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
Inference Config:
{'pretrained_model_path': './models/Model/stable-diffusion-v1-5', 'motion_module_path': './models/live2diff.ckpt', 'depth_model_path': './models/dpt_hybrid_384.pt', 'unet_additional_kwargs': {'cond_mapping': True, 'use_inflated_groupnorm': True, 'use_motion_module': True, 'motion_module_resolutions': [1, 2, 4, 8], 'unet_use_cross_frame_attention': False, 'unet_use_temporal_attention': False, 'motion_module_type': 'Streaming', 'motion_module_kwargs': {'num_attention_heads': 8, 'num_transformer_block': 1, 'attention_block_types': ['Temporal_Self', 'Temporal_Self'], 'temporal_position_encoding': True, 'temporal_position_encoding_max_len': 24, 'temporal_attention_dim_div': 1, 'zero_initialize': True, 'attention_class_name': 'stream', 'attention_kwargs': {'window_size': 16, 'sink_size': 8}}}, 'noise_scheduler_kwargs': {'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'linear', 'steps_offset': 1, 'clip_sample': False}, 'prompt_template': 'masterpiece, best quality, intricate, print, pattern, {}', 'third_party_dict': {'dreambooth': './models/Model/disneyPixarCartoon_v10.safetensors', 'clip_skip': 2}, 'num_inference_steps': 10, 't_index_list': [0, 2, 4]}
Convert input prompt to "masterpiece, best quality, intricate, print, pattern, 1man is talking".
loaded 3D unet's pretrained weights from ./models/Model/stable-diffusion-v1-5/unet ...
### missing keys: 576; 
### unexpected keys: 0;
### Motion Module Parameters: 417.1376 M
/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/animatediff/pipeline/pipeline_animatediff_depth.py:281: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  mm_checkpoint = torch.load(motion_module_path, map_location="cuda")
global_step: 191999
missing keys: 686, unexpected keys: 0
/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/MiDaS/midas/base_model.py:11: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  parameters = torch.load(path, map_location=torch.device('cpu'))
Pipeline class: <class 'live2diff.pipeline_stream_animation_depth.StreamAnimateDiffusionDepth'>
Few-step LoRA: latent-consistency/lcm-lora-sdv1-5
t_index_list is passed: [0, 2, 4]. Number Inference Steps: 10, equivalents to strength 1.0.
loaded 3D unet's pretrained weights from ./models/Model/stable-diffusion-v1-5/unet ...
### missing keys: 576; 
### unexpected keys: 0;
### Motion Module Parameters: 417.1376 M
/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/animatediff/pipeline/pipeline_animatediff_depth.py:327: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  mm_checkpoint = torch.load(motion_module_path, map_location="cpu")
global_step: 191999
missing keys: 686, unexpected keys: 0
Load Warmup UNet.
/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
The config attributes {'shift_factor': 0.0, 'upsample_fn': 'nearest'} were passed to AutoencoderTiny, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading TensorRT engine: engines/disneyPixarCartoon_v10--lcm--step3--tiny_vae-True--h-512--w-512/unet/unet.engine
[I] Loading bytes from engines/disneyPixarCartoon_v10--lcm--step3--tiny_vae-True--h-512--w-512/unet/unet.engine
[E] 1: [defaultAllocator.cpp::allocate::19] Error Code 1: Cuda Runtime (out of memory)
[W] Requested amount of GPU memory (943728128 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[E] 2: [executionContext.cpp::ExecutionContext::552] Error Code 2: OutOfMemory (no further information)
Loading TensorRT engine: engines/disneyPixarCartoon_v10--lcm--step3--tiny_vae-True--h-512--w-512/depth/midas.engine
[I] Loading bytes from engines/disneyPixarCartoon_v10--lcm--step3--tiny_vae-True--h-512--w-512/depth/midas.engine
[E] 1: [defaultAllocator.cpp::allocate::19] Error Code 1: Cuda Runtime (out of memory)
[W] Requested amount of GPU memory (670629888 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[E] 2: [executionContext.cpp::ExecutionContext::552] Error Code 2: OutOfMemory (no further information)
Loading TensorRT engine: engines/disneyPixarCartoon_v10--lcm--step3--tiny_vae-True--h-512--w-512/vae/vae_encoder.engine
[I] Loading bytes from engines/disneyPixarCartoon_v10--lcm--step3--tiny_vae-True--h-512--w-512/vae/vae_encoder.engine
Loading TensorRT engine: engines/disneyPixarCartoon_v10--lcm--step3--tiny_vae-True--h-512--w-512/vae/vae_decoder.engine
[I] Loading bytes from engines/disneyPixarCartoon_v10--lcm--step3--tiny_vae-True--h-512--w-512/vae/vae_decoder.engine
[E] 1: [defaultAllocator.cpp::allocate::19] Error Code 1: Cuda Runtime (out of memory)
[W] Requested amount of GPU memory (805306368 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[E] 2: [executionContext.cpp::ExecutionContext::552] Error Code 2: OutOfMemory (no further information)
[E] 1: [defaultAllocator.cpp::allocate::19] Error Code 1: Cuda Runtime (out of memory)
[E] 2: [executionContext.cpp::ExecutionContext::552] Error Code 2: OutOfMemory (no further information)
TensorRT acceleration enabled.
Traceback (most recent call last):
  File "/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/test.py", line 211, in <module>
    fire.Fire(main)
  File "/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/test.py", line 160, in main
    warmup_results = stream.prepare(
  File "/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/utils/wrapper.py", line 189, in prepare
    warmup_frames = self.stream.prepare(
  File "/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/pipeline_stream_animation_depth.py", line 309, in prepare
    warmup_x_t = self.encode_image(warmup_x)
  File "/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/pipeline_stream_animation_depth.py", line 526, in encode_image
    img_latent = retrieve_latents(self.vae.encode(image_tensors), self.generator)
  File "/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/acceleration/tensorrt/engine.py", line 72, in encode
    self.encoder.allocate_buffers(
  File "/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/acceleration/tensorrt/utilities.py", line 263, in allocate_buffers
    self.context.set_input_shape(binding, shape)
AttributeError: 'NoneType' object has no attribute 'set_input_shape'

``` 
Additionally, acceleration fails when running with `t_index_list: [0, 1, 2, 3, 4] num_inference_steps: 50 strength: 0.1`, please see below: 

```
/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
Inference Config:
{'pretrained_model_path': './models/Model/stable-diffusion-v1-5', 'motion_module_path': './models/live2diff.ckpt', 'depth_model_path': './models/dpt_hybrid_384.pt', 'unet_additional_kwargs': {'cond_mapping': True, 'use_inflated_groupnorm': True, 'use_motion_module': True, 'motion_module_resolutions': [1, 2, 4, 8], 'unet_use_cross_frame_attention': False, 'unet_use_temporal_attention': False, 'motion_module_type': 'Streaming', 'motion_module_kwargs': {'num_attention_heads': 8, 'num_transformer_block': 1, 'attention_block_types': ['Temporal_Self', 'Temporal_Self'], 'temporal_position_encoding': True, 'temporal_position_encoding_max_len': 24, 'temporal_attention_dim_div': 1, 'zero_initialize': True, 'attention_class_name': 'stream', 'attention_kwargs': {'window_size': 16, 'sink_size': 8}}}, 'noise_scheduler_kwargs': {'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'linear', 'steps_offset': 1, 'clip_sample': False}, 'prompt_template': 'masterpiece, best quality, intricate, print, pattern, {}', 'third_party_dict': {'dreambooth': './models/Model/disneyPixarCartoon_v10.safetensors', 'clip_skip': 2}, 'num_inference_steps': 50, 't_index_list': [30, 36, 42]}
Convert input prompt to "masterpiece, best quality, intricate, print, pattern, 1man is talking".
loaded 3D unet's pretrained weights from ./models/Model/stable-diffusion-v1-5/unet ...
### missing keys: 576; 
### unexpected keys: 0;
### Motion Module Parameters: 417.1376 M
/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/animatediff/pipeline/pipeline_animatediff_depth.py:281: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  mm_checkpoint = torch.load(motion_module_path, map_location="cuda")
global_step: 191999
missing keys: 686, unexpected keys: 0
/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/MiDaS/midas/base_model.py:11: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  parameters = torch.load(path, map_location=torch.device('cpu'))
Pipeline class: <class 'live2diff.pipeline_stream_animation_depth.StreamAnimateDiffusionDepth'>
Few-step LoRA: latent-consistency/lcm-lora-sdv1-5
Generate t_index_list: [0, 1, 2, 3, 4] via num_inference_steps: 50, strength: 0.1
loaded 3D unet's pretrained weights from ./models/Model/stable-diffusion-v1-5/unet ...
### missing keys: 576; 
### unexpected keys: 0;
### Motion Module Parameters: 417.1376 M
/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/animatediff/pipeline/pipeline_animatediff_depth.py:327: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  mm_checkpoint = torch.load(motion_module_path, map_location="cpu")
global_step: 191999
missing keys: 686, unexpected keys: 0
Load Warmup UNet.
/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
The config attributes {'shift_factor': 0.0, 'upsample_fn': 'nearest'} were passed to AutoencoderTiny, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading TensorRT engine: engines/disneyPixarCartoon_v10--lcm--step5--tiny_vae-True--h-512--w-512/unet/unet.engine
[I] Loading bytes from engines/disneyPixarCartoon_v10--lcm--step5--tiny_vae-True--h-512--w-512/unet/unet.engine
[E] 1: [defaultAllocator.cpp::allocate::19] Error Code 1: Cuda Runtime (out of memory)
[W] Requested amount of GPU memory (1180463648 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[E] 2: [safeDeserialize.cpp::load::269] Error Code 2: OutOfMemory (no further information)
[!] Could not deserialize engine. See log for details.
Traceback (most recent call last):
  File "/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/utils/wrapper.py", line 613, in _load_model
    stream.unet = UNet2DConditionModelDepthEngine(unet_path, cuda_stream, use_cuda_graph=False)
  File "/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/acceleration/tensorrt/engine.py", line 126, in __init__
    self.engine.load()
  File "/home/hovhannesmargaryan/Desktop/open-source/Live2Diff/live2diff/acceleration/tensorrt/utilities.py", line 238, in load
    self.engine = engine_from_bytes(bytes_from_path(self.engine_path))
  File "<string>", line 3, in engine_from_bytes
  File "/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/polygraphy/backend/base/loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
  File "/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/polygraphy/util/util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/polygraphy/backend/trt/loader.py", line 665, in call_impl
    G_LOGGER.critical("Could not deserialize engine. See log for details.")
  File "/home/hovhannesmargaryan/miniconda3/envs/live2diff/lib/python3.10/site-packages/polygraphy/logger/logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Could not deserialize engine. See log for details.
Acceleration has failed. Falling back to normal mode.
```

**Comment by LeoXing1996** [comment]
@marghovo, could you please modify t_index_list in disneyPixar.yaml to [36, 42] and check if the OOM error persists?

**Comment by marghovo** [comment]
@LeoXing1996, yes unfortunately the OOM error still persists with `t_index_list is passed: [36, 42]. Number Inference Steps: 50, equivalents to strength 0.28`.

**Comment by LeoXing1996** [comment]
@marghovo This is quite unusual. Are you running any other programs on your GPU? What is the available memory before you set up Live2Diff inference?

**Comment by marghovo** [comment]
@LeoXing1996, I am not running anything else but the inference of Live2Diff? My GPU memory is `16376MiB`. Is it possible that I should have at least 24GB to run it? Though, I was able to run the inference without TensorRT with  `16376MiB`.

Also, I have another question? Did you only test on RTX 4090? I seem to have similar issue on H100 when building the engines.

**Comment by LeoXing1996** [comment]
@marghovo , I only tested on RTX 4090 - 24G and A100. I'm not sure the TensorRT version in requirements.txt fit H100 GPU.

**Comment by marghovo** [comment]
@LeoXing1996 , perfect. Thanks for your help.
